# Generated by Django 4.0.1 on 2022-01-31 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('taste', models.CharField(max_length=45)),
                ('how_strong', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='alcoholCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbrownia.alcohol')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbrownia.client')),
            ],
        ),
        migrations.AddField(
            model_name='alcohol',
            name='alcohol_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bimbrownia.alcoholcategory'),
        ),
    ]
